version: '3.0'

services:
  nginx:
    image: nginx
    depends_on:
      - php
    volumes:
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
#      - ./logs/php_errors.log:/var/log/nginx/error.log
      - ./:/var/www/html/
    networks:
      - backend
    ports:
      - "${PUBLIC_APP_PORT}:80"

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html/
    networks:
      - backend
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.88.226 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"   

  mysql:
    env_file: .env   
    build: 
      context: ./docker/mysql
    restart: always
    ports:
      - "${PUBLIC_MYSQL_PORT}:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - backend      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - backend
    ports:
      - "${PUBLIC_APP_PHPMYADMIN_PORT}:80"

networks:
  backend:
    driver: "bridge"